### ISSUE TITLE
Website pages have no vertical/horizontal scroll bars

### ISSUE THREAD

**Issue by Swagmoneydre69** [rcos/CSCI-4470-OpenSource#79]
For some of the pages, you can't access some of the page because there are no scroll bars. This should be fixed so the whole page can be seen 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5789868/233729265-deb657cd-ed69-4e33-aa5b-eaa4c57b8a74.png">

**Comment by nazime1** [comment]
Probably should have made a PR or something but as of [this commit](https://github.com/rcos/CSCI-4470-OpenSource/commit/21cdf416e55914df4912765c0d09a2cd9888813d) this issue is fixed.
